[package]
name = "macro_counter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mctr"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.5"
chrono = "0.4"
dirs = "5.0.1"
